DATABASE_HOST: localhost
DATABASE_PORT: 3306
DATABASE_NAME: banco
DATABASE_USERNAME: root
DATABASE_PASSWORD: root

OUTER_TABLES_SCRIPT: script.sql
CUSTOM_SELECT_FILE: custom_select.txt

SQLITE_OUTPUT_NAME: ic.db

IGNORED_TABLES:
  - table1

IGNORED_INSERTS:
  - table1