CREATE TABLE table1 (
	a	INTEGER UNIQUE,
	b	INTEGER PRIMARY KEY AUTOINCREMENT,
	c	INTEGER,
	d	INTEGER NOT NULL
);
CREATE TABLE table2 (
	a	INTEGER UNIQUE,
	b	INTEGER PRIMARY KEY AUTOINCREMENT,
	c	INTEGER,
	d	INTEGER NOT NULL
);